name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build this project and deploy on production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencied
        run: npm ci

      - name: Build Project
        run: npm run build --if-present

      - name: Deploying to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }}
          publish_dir: ./dist
          external_repository: tj-dsk-tpp/tj-dsk-tpp.github.io
          publish_branch: main
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
